version: "3.7"

services:
  apple:
    build: 
      context: .
    networks:
      - public
    volumes:
      - .:/app
    labels:
      - traefik.enable=true
      - traefik.http.routers.apple-http.rule=Host(`apple.tranvannhut.com`)
      - traefik.http.routers.apple-http.entrypoints=http
      - traefik.http.routers.apple-http.middlewares=redirect

      - traefik.http.routers.apple-https.rule=Host(`apple.tranvannhut.com`)
      - traefik.http.routers.apple-https.entrypoints=https
      - traefik.http.routers.apple-https.tls=true
      - traefik.http.routers.apple-https.tls.certresolver=letsencrypt

      - traefik.http.middlewares.redirect.redirectscheme.scheme=https
      - traefik.http.services.apple.loadbalancer.server.port=3000
      # - traefik.enable=true
      # - traefik.http.routers.web.rule=Host(`apple.tranvannhut.com`)
      # - traefik.http.services.web.loadbalancer.server.port=3000
networks:
  public:
    external: true