version: "3.7"

services:
  proxy:
    image: traefik:2.3
    ports:
      - 5000:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  web:
    build: Dockerfile
    labels:
        - traefik.enable=true
        - traefik.http.routers.web.rule=Host(`apple.tranvannhut.com`)
        - traefik.http.services.web.loadbalancer.server.port=3000
