version: "3.7"

services:
  web:
    build: 
      context: .
    networks:
      - public
    labels:
      - traefik.enable=true
      - traefik.http.routers.web-http.rule=Host(`apple.tranvannhut.com`)
      - traefik.http.routers.web-http.entrypoints=http
      - traefik.http.routers.web-http.middlewares=redirect

      - traefik.http.routers.web-https.rule=Host(`apple.tranvannhut.com`)
      - traefik.http.routers.web-https.entrypoints=https
      - traefik.http.routers.web-https.tls=true
      - traefik.http.routers.web-https.tls.certresolver=letsencrypt

      - traefik.http.middlewares.redirect.redirectscheme.scheme=https
      - traefik.http.services.web.loadbalancer.server.port=3000
      # - traefik.enable=true
      # - traefik.http.routers.web.rule=Host(`apple.tranvannhut.com`)
      # - traefik.http.services.web.loadbalancer.server.port=3000
