version: "3.7"

services:
  web:
    build: 
      context: .
    networks:
      - public
    labels:
      - traefik.enable=true
      - traefik.http.routers.web.rule=Host(`apple.tranvannhut.com`)
      - traefik.http.services.web.loadbalancer.server.port=3000
