version: "3.7"

services:
  proxy:
    image: traefik:2.3
    ports:
      - 5000:80
    command: 
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
    labels:
        - traefik.enable=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  web:
    build: 
      context: .
    labels:
        - traefik.enable=true
        - traefik.http.routers.web.rule=Host(`apple.tranvannhut.com`)
        - traefik.http.services.web.loadbalancer.server.port=3000
